services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=
      - NEXT_PUBLIC_BUILD_STATIC_EXPORT=false
    depends_on:
      - backend
    volumes:
      # For development - uncomment these lines for hot reload
      # - ./src:/app/src
      # - ./public:/app/public
      - /app/node_modules
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:admin@database:5432/healthcare_analysis
    volumes:
      - ./backend/service-account-key.json:/app/service-account-key.json:ro
      - ./backend/logs:/app/logs
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=healthcare_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: