services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SERVER_URL=http://localhost:5000
      - NEXT_PUBLIC_BUILD_STATIC_EXPORT=false
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    command: yarn dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:admin@database:5432/healthcare_analysis
    volumes:
      - ./backend:/app
      - ./backend/service-account-key.json:/app/service-account-key.json:ro
    depends_on:
      - database
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=healthcare_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: